name = "data-brain-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "data-brain-db"
database_id = "98254ae4-dc04-44f2-bd00-67b2dd0a3ba4"

[vars]
ENVIRONMENT = "production"

[env.staging]
name = "data-brain-api-staging"
[env.staging.vars]
ENVIRONMENT = "staging"
